project:
  type: website
  output-dir: docs
  resources: 
    - assets/json/*
  preview:
    port: 4200
    browser: true
    watch-inputs: true

execute:
  freeze: auto

filters:
  - auto-dark
  - code-visibility

format:
  html:
    include-in-header:
#      - file: assets/html/toggle-hide-navbar.html
      - file: assets/html/freezeframe.html
    theme:
      light: [cosmo, assets/css/theme-quarto.scss]      
    css: 
      - assets/css/styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    html-math-method: katex
    number-sections: false
    code-fold: false
    smooth-scroll: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

website:
  title: "Julia course"
  image: assets/images/logo-julia.png
  favicon: assets/images/logo-julia.svg
  reader-mode: true
  open-graph: true
  twitter-card: true
  site-url: https://ocourses.github.io/course-tse-julia/
  repo-url: https://github.com/ocourses/course-tse-julia
  issue-url: https://github.com/ocourses/course-tse-julia/issues/new/choose
  repo-actions: [edit, source, issue]
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  search: 
    location: navbar
    show-item-context: true
    type: overlay
    keyboard-shortcut: ["?", "H"]
  page-footer: 
    center: "Copyright 2025, Olivier Cots"
  navbar:
    background: light
    logo: assets/images/logo-julia.svg
    logo-alt: "Julia course."
    title: false
    tools:
      - icon: github
        href: https://github.com/ocourses/course-tse-julia
    left:
      - text: "Content of the course"
        href: src/index.qmd
  sidebar:
    - id: M1
      style: "floating"
      collapse-level: 2
      contents:
        - section: "Introduction"
          contents:
          - text: Why Julia?
            href: src/why_julia.qmd
          - text: Getting started
            href: src/getting_started.qmd
          - text: Developer set up
            href: src/developer_setup.qmd
          - text: Foretaste of Julia Code
            href: src/foretaste_of_julia_code.qmd
        - section: "Julia language"
          contents:
          - text: Core Syntax and Operations
            href: src/syntax.qmd
          - text: Structure your code
            href: src/structure.qmd
          - text: Types
            href: src/types.qmd
          - text: Type stability for performance
            href: src/performance.qmd
          - text: Auto-evaluation
            href: src/eval.qmd
        - section: "Applications"
          contents:
          - text: Root-Finding Methods
            href: src/root_finding.qmd
          - text: Machine Learning
            href: src/machine_learning.qmd